### ISSUE TITLE
reflect-metadata shim - post beta blues

### ISSUE THREAD

**Issue by matt4446** [matt4446/WhatsMyScore2-NativeScript#1]
All working before RC ... 

```java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/whatsmyscore.breakoutdeveloper.com/files/app/app.js

reflect-metadata shim is required when using class decorators
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'require', file:'', line: 1, column: 266

```
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Caused by: com.tns.NativeScriptException: ```

or ... putting it back in ... 

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/whatsmyscore.breakoutdeveloper.com/files/app/app.js

TypeError
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'decorate', file:'/data/data/whatsmyscore.breakoutdeveloper.com/files/app/tns_modules/reflect-metadata/Reflect.js', line: 76, column: 23
    Frame: function:'__decorate', file:'/data/data/whatsmyscore.breakoutdeveloper.com/files/internal/ts_helpers.js', line: 10, column: 96
    Frame: function:'', file:'/data/data/whatsmyscore.breakoutdeveloper.com/files/app/controls/icons/ion-icon.js', line: 96, column: 5
    Frame: function:'', file:'/data/data/whatsmyscore.breakoutdeveloper.com/files/app/controls/icons/ion-icon.js', line: 118, column: 2
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/whatsmyscore.breakoutdeveloper.com/files/app/controls/nav/nav.js', line: 5, column: 18
    Frame: function
```

[angular2 issus](https://github.com/angular/angular/issues/5306) suggest that it should not be included as:

``` js
import 'reflect-metadata';

```

but the script should be included instead.

**Comment by matt4446** [comment]
https://github.com/matt4446/WhatsMyScore2-NativeScript/commit/49874c859f7968c52a9d05a85fd3ddde0a01c54f fixed it
